"""Service layer for character relationship CRUD and delta application (facade).

Milestone 6B (decomposition.md §4.4): implementation moved to the
``app/relationships/`` package (crud, validation, deltas, blocks, issues,
decay, memory_feed, trajectory). This module stays as a thin facade that
re-exports the full public API — test patch contracts
(``app.relationship_service.{settings, _maybe_create_memory_from_event,
_dynamic_decay_factor, ...}``), routers and pipeline consumers keep working.
Removal of the facade is planned for Sprint 10.
"""

from .relationships import (
    FAMILY_TYPES,
    MAX_DELTA,
    TRANSITIONS,
    VALID_TYPES,
    apply_decay,
    apply_delta,
    apply_issue_deltas,
    apply_saturation_guard,
    build_behavior_drivers_block,
    build_epistemic_mask_block,
    build_open_issues_block,
    build_relationships_block,
    build_trajectory_block,
    clamp_metric,
    compute_proactive_boost,
    compute_reciprocity_belief_multiplier,
    create_issue,
    format_relationship_for_prompt,
    get_or_create_relationship,
    get_recent_events,
    get_relationship,
    get_trajectory_events,
    is_family_type,
    list_issues_for_chat,
    list_open_issues,
    list_received_relationships,
    list_relationships_for_chat,
    list_relationships_for_character,
    list_top_open_issues_for_character,
    proactive_boost_from_issues,
    prune_relationship_events,
    recent_gain,
    resolve_issue,
    sanitize_issue_text,
    scale_delta_by_resistance,
    tick_open_issues,
    touch_issue,
    trajectory_metric_gain,
    update_relationship_fields,
    validate_relationship_type_update,
    validate_transition,
)
from .relationships import (
    _clamp_delta,
    _dynamic_decay_factor,
    _log_relationship_event,
    _maybe_create_memory_from_event,
    _maybe_create_memory_from_resolved_issue,
)
from .config import settings
from .models import RelationshipEvent

__all__ = [
    "settings",
    "RelationshipEvent",
    "FAMILY_TYPES",
    "TRANSITIONS",
    "VALID_TYPES",
    "MAX_DELTA",
    "apply_decay",
    "apply_delta",
    "apply_issue_deltas",
    "apply_saturation_guard",
    "build_behavior_drivers_block",
    "build_epistemic_mask_block",
    "build_open_issues_block",
    "build_relationships_block",
    "build_trajectory_block",
    "clamp_metric",
    "compute_proactive_boost",
    "compute_reciprocity_belief_multiplier",
    "create_issue",
    "format_relationship_for_prompt",
    "get_or_create_relationship",
    "get_recent_events",
    "get_relationship",
    "get_trajectory_events",
    "is_family_type",
    "list_issues_for_chat",
    "list_open_issues",
    "list_received_relationships",
    "list_relationships_for_chat",
    "list_relationships_for_character",
    "list_top_open_issues_for_character",
    "proactive_boost_from_issues",
    "prune_relationship_events",
    "recent_gain",
    "resolve_issue",
    "sanitize_issue_text",
    "scale_delta_by_resistance",
    "tick_open_issues",
    "touch_issue",
    "trajectory_metric_gain",
    "update_relationship_fields",
    "validate_relationship_type_update",
    "validate_transition",
    "_clamp_delta",
    "_dynamic_decay_factor",
    "_log_relationship_event",
    "_maybe_create_memory_from_event",
    "_maybe_create_memory_from_resolved_issue",
]
